# Copyright (c) 2026 Fallen01135. All rights reserved.
# Licensed under the Fallen01135 Mod License (see LICENSE.md).

#!/usr/bin/env python3
"""Generate a C++ settings header from a TSV definition.

The TSV needs the columns Name, Section, Type and Default. Optional columns:
IsHex, Condition (a C++ expression using `value`) and Comment.

Example:
    python generate_settings.py --input config/settings.tsv --output build/generated/Settings.hpp
"""

import argparse
import csv
import sys
from pathlib import Path

REQUIRED_COLUMNS = ("Name", "Section", "Type", "Default")
LIB_NAMESPACE = "SettingsLib"


def parse_args() -> argparse.Namespace:
	p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	p.add_argument("--input", required=True, type=Path, help="Path to the settings TSV")
	p.add_argument("--output", required=True, type=Path, help="Path of the header to generate")
	p.add_argument("--library-include", default="SimpleSettings.hpp",
		help="Include path of SimpleSettings.hpp (default: %(default)s)")
	p.add_argument("--namespace", default="", help="Namespace for the struct, empty for none")
	p.add_argument("--struct-name", default="Settings", help="Name of the generated struct (default: %(default)s)")
	p.add_argument("--compact", action="store_true", help="One line per setting instead of one line per argument")
	p.add_argument("--group-by-section", action="store_true",
		help="Wrap settings in a sub struct per section, e.g. Settings::General::mySetting")
	return p.parse_args()


def fail(message: str) -> None:
	print(f"generate_settings: error: {message}", file=sys.stderr)
	sys.exit(1)


def read_settings(path: Path) -> list[dict[str, str]]:
	if not path.is_file():
		fail(f"{path} not found")

	with path.open(encoding="utf-8-sig", newline="") as f:
		reader = csv.DictReader(f, delimiter="\t")
		missing = [c for c in REQUIRED_COLUMNS if c not in [(n or "").strip() for n in (reader.fieldnames or [])]]
		if missing:
			fail(f"{path.name} is missing required column(s): {', '.join(missing)}")

		rows = []
		for line_no, row in enumerate(reader, start=2):
			clean = {(k or "").strip(): (v or "").strip() for k, v in row.items() if k}
			if not any(clean.values()):
				continue
			for column in REQUIRED_COLUMNS:
				if not clean.get(column) and column != "Default":
					fail(f"{path.name}:{line_no}: empty value in column '{column}'")
			rows.append(clean)

	names = [r["Name"] for r in rows]
	duplicates = sorted({n for n in names if names.count(n) > 1})
	if duplicates:
		fail(f"duplicate setting name(s): {', '.join(duplicates)}")

	return rows


def cpp_string(text: str) -> str:
	"""Return text as a valid C++ string literal."""
	escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")
	return f'"{escaped}"'


def format_default(type_str: str, raw: str) -> str:
	t = type_str.lower()
	is_string = "string" in t
	is_bool = "bool" in t

	if "vector" in t:
		parts = [p.strip() for p in raw.split(",") if p.strip()]
		if is_string:
			parts = [cpp_string(p) for p in parts]
		elif is_bool:
			parts = [p.lower() for p in parts]
		return "{ " + ", ".join(parts) + " }" if parts else "{}"

	if is_string:
		return cpp_string(raw)
	if is_bool:
		return raw.lower()
	return raw


def build_args(s: dict[str, str]) -> list[str]:
	type_str = s["Type"]
	is_hex = s.get("IsHex", "").lower() == "true"
	condition = s.get("Condition", "")
	comment = s.get("Comment", "")

	args = [cpp_string(s["Section"]), cpp_string(s["Name"]), format_default(type_str, s["Default"])]

	validator = f"[](const {type_str}& value) {{ return {condition}; }}" if condition else "nullptr"
	comment_val = cpp_string(comment) if comment else "nullptr"

	# Optional arguments are positional, so later ones force the earlier ones.
	if is_hex or condition or comment:
		args.append(comment_val)
	if is_hex or condition:
		args.append(validator)
	if is_hex:
		args.append("true")
	return args


def generate(settings: list[dict[str, str]], args: argparse.Namespace) -> str:
	lines: list[str] = []
	ns = args.namespace.strip()

	def emit(level: int, text: str = "") -> None:
		lines.append(("\t" * level + text) if text else "")

	emit(0, "#pragma once")
	emit(0)
	emit(0, f'#include "{args.library_include}"')
	for header in ("functional", "string", "tuple", "vector"):
		emit(0, f"#include <{header}>")
	emit(0)
	emit(0, "/**")
	emit(0, f" * GENERATED CODE - DO NOT MODIFY MANUALLY.")
	emit(0, f" * Source: {args.input.name} (generated by tools/{Path(__file__).name})")
	emit(0, " */")

	base = 0
	if ns:
		emit(0, f"namespace {ns}")
		emit(0, "{")
		base = 1

	emit(base, f"struct {args.struct_name}")
	emit(base, "{")

	sections: dict[str, list[dict[str, str]]] = {}
	for s in settings:
		sections.setdefault(s["Section"], []).append(s)

	refs: list[str] = []
	item_level = base + 2 if args.group_by_section else base + 1

	for sec_name, items in sections.items():
		if args.group_by_section:
			emit(base + 1, f"struct {sec_name}")
			emit(base + 1, "{")

		for s in items:
			name = s["Name"]
			decl = f"inline static {LIB_NAMESPACE}::Item<{s['Type']}> {name}"
			item_args = build_args(s)

			if args.compact:
				emit(item_level, f"{decl}{{ {', '.join(item_args)} }};")
			else:
				emit(item_level, decl)
				emit(item_level, "{")
				for i, a in enumerate(item_args):
					emit(item_level + 1, a + ("," if i < len(item_args) - 1 else ""))
				emit(item_level, "};")
				emit(0)

			refs.append(f"{sec_name}::{name}" if args.group_by_section else name)

		if args.group_by_section:
			emit(base + 1, "};")
			emit(0)

	emit(base + 1, "static constexpr auto ALL = std::make_tuple")
	emit(base + 1, "(")
	for i, ref in enumerate(refs):
		emit(base + 2, f"std::ref({ref})" + ("," if i < len(refs) - 1 else ""))
	emit(base + 1, ");")
	emit(base, "};")

	if ns:
		emit(0, "}")

	return "\n".join(lines) + "\n"


def main() -> None:
	args = parse_args()
	content = generate(read_settings(args.input), args)

	# Only touch the file when something changed, so the build does not recompile for nothing.
	if args.output.is_file() and args.output.read_text(encoding="utf-8") == content:
		return

	args.output.parent.mkdir(parents=True, exist_ok=True)
	args.output.write_text(content, encoding="utf-8", newline="\n")
	print(f"Generated {args.output} from {args.input.name}")


if __name__ == "__main__":
	main()
