blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/c99MyyPzhJ
    about: Ask questions, get help, or chat with the community on Discord.
  - name: Nexus Mods Comments
    url: https://www.nexusmods.com/skyrimspecialedition/mods/117661?tab=posts
    about: Post questions, general feedback, or suggestions on the official mod page.
