[General]

# If the 24 hours clock should be used or the 12 hours clock
bUse24Clock = true

# If a zero should be added to every number if they are not having 2 digits. Only works for the time, not the date.
bUseLeadingZero = true

# This is the date string found ingame. For more information check: https://github.com/users/Fallen01135/projects/3?pane=issue&itemId=200072401
sDateString = {DD}, {dd}. {MM} {YY}